### ISSUE TITLE
import menuinst fails during conda install

### ISSUE THREAD

**Issue by flutefreak7** [conda/menuinst#16]
I'm on Windows 7 64-bit and was trying to update my anaconda root environment from python 3.4 to 3.5.

When I ran `conda install anaconda python=3.5` in an Administrator cmd prompt, after all the downloads, and after extracting, I got the following Traceback:

```
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\conda\install.py", line 326, in mk_menus
    import menuinst
  File "C:\Anaconda3\lib\site-packages\menuinst\__init__.py", line 19, in <modul
    from .win32 import Menu, ShortCut
  File "C:\Anaconda3\lib\site-packages\menuinst\win32.py", line 13, in <module>
    from .winshortcut import create_shortcut
ImportError: No module named 'menuinst.winshortcut'
```

I see that winshortcut is a *.cpp file which is different from the other submodules of menuist, so I figure that might be an issue?

This is crashing the install, so any help is appreciated.

**Comment by msarahan** [comment]
Please see https://github.com/conda/conda/issues/1762#issuecomment-153366413

Menuinst should be installed by your command, but the solver isn't picking it up for some reason.  We will investigate.  Please try to install it manually for now.

**Comment by flutefreak7** [comment]
I actually was able to solve it by first running `conda update conda python=3.5` then running `conda update anaconda` which picked up the python version as 3.5 and updated anaconda accordingly.  I thought to do this because I've seen other instructions that began with `conda update conda`, so I thought it might be a prudent first step to update the updater.

**Comment by msarahan** [comment]
Cool.  Thanks for posting your solution.

**Comment by YSGitProjects** [comment]
This still exists for me upgrading from python 3.7.2 to python 3.8.1

    from .winshortcut import create_shortcut
ModuleNotFoundError: No module named 'menuinst.winshortcudone
