### ISSUE TITLE
Add Windows Terminal profile option

### ISSUE THREAD

**Issue by marcoesters** [conda/menuinst#196]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

The Windows Terminal app contains profiles for terminal-based applications. These are stored in a `settings.json` file that can be appended. The [Microsoft documentation](https://learn.microsoft.com/en-us/windows/terminal/dynamic-profiles) contains a few examples of dynamic profiles.

### Why is this needed?

Conda packages such as the console shortcuts for Miniconda, Anaconda Distribution, and Miniforge can be opened in the Windows Terminal, but do not appear in the profile list. This would be a great convenience feature to use the tab feature of the Windows Terminal instead of having to open a new Window each time.

### What should happen?

A new option should be added to allow adding Windows Terminal profiles.

### Additional Context

This is currently focused on the Windows Terminal, but the schema should be updated such that it could potentially be expanded to other platforms if the profile config files have plain-text configuration files.

**Comment by jypeter** [comment]
That's nice, @marcoesters ! Just what I was looking for using Google, and not finding any nice/streamlined steps that don't involve manually editing the Terminal json config file

The trouble is that I have checked the current [menuinst documentation](https://conda.github.io/menuinst/) and I have not found any obvious and easy way to add a new profile to my Windows Terminal.

Can we use something similar to what is described in menuinst [Usage](https://conda.github.io/menuinst/getting-started/#usage) :  `python -c "from menuinst.api import install; install('path/to/menu.json')"`

Thanks!

**Comment by marcoesters** [comment]
You can install it the same way, you just need to add the `terminal_profile` option to the Windows part of your config file. See the schema: https://conda.github.io/menuinst/reference/#menuinst._schema.Windows.terminal_profile

Be advised though that this will also create a Start Menu entry - I don't think this can be skipped yet.
