### ISSUE TITLE
Change the API to menuinst.install(path_or_dict)

### ISSUE THREAD

**Issue by anntzer** [conda/menuinst#25]
All's in the title: allowing passing a dict (basically, the contents of the json file) to `menuinst.install` would simplify programmatic use of menuinst.  Alternatively, another function (`install_from_dict`) would be fine too.

**Comment by anntzer** [comment]
bump?

**Comment by msarahan** [comment]
This is a good idea, but I'm afraid we don't really have time to implement these nice-to-have features.  I'd be happy to look over a PR if you have time to submit one.
