### ISSUE TITLE
Support `NSSupportsAutomaticGraphicsSwitching` on macOS

### ISSUE THREAD

**Issue by wolfv** [conda/menuinst#280]
This got auto-completed for me and I think we have a similar setting on Linux. Not sure how relevant it is at this point in time, but I did find a number of occurences on Github.

**Comment by jaimergp** [comment]
It's there already, isn't it?

https://github.com/conda/menuinst/blob/2cfdf133f65cdd45ab05129b368eaa5cd2c06170/menuinst/_schema.py#L314
