### ISSUE TITLE
pywin32 dependency / size of menuinst in Miniconda etc.

### ISSUE THREAD

**Issue by mbargull** [conda/menuinst#41]
Since #27 `win_elevate.py` is included, which is great since it resolved interactive elevation. This added `pywin32` as a dependency though.
Since `pywin32` is a rather "heavy" package, now `menuinst` (with its dependency) will account for a considerable size of minimal installers like Miniconda.
Sadly, I do not know of an alternative to `pywin32` which provides similar functionality for Windows' interactive UAC.

**Comment by isuruf** [comment]
pywin32 removed in #103
