### ISSUE TITLE
Add CI for osx and linux

### ISSUE THREAD

**Issue by goanpeca** [conda/menuinst#51]

**Comment by jakirkham** [comment]
Does this mean macOS and Linux are supported (or will be again)? Was a little confused by the note in the README, which made it sound like they are not supported.

**Comment by mbargull** [comment]
They aren't yet, but @goanpeca wrote down some initial ideas for that in https://github.com/ContinuumIO/menuinst/issues/48.

**Comment by jakirkham** [comment]
Presumably we will still want this given there is interest in adding macOS and Linux support ( https://github.com/conda/menuinst/issues/48#issuecomment-943154918 )

**Comment by jaimergp** [comment]
The `cep-devel` branch has support (and CI) for macOS and Linux. I don't know if we want to close this now or when that branch makes it to main (pending CEP approval).
