### ISSUE TITLE
windows.knownfolders.get_path uses incorrect locale handling

### ISSUE THREAD

**Issue by zooba** [conda/menuinst#54]
At [knownfolders.py#L213](https://github.com/ContinuumIO/menuinst/blob/master/menuinst/windows/knownfolders.py#L213) we see this code:

```python
    # convert to unicode
    codec = sys.getdefaultencoding()
    if not codec:
        codec="utf-8"
    if hasattr(path, "decode"):
        path = path.decode(codec)
```

This entire block is incorrect and unnecessary, and actually broken on Python 2:
* `sys.getdefaultencoding()` is for transparently converting between `str` and `unicode` (**`ascii` on Python 2!**) - you actually want `sys.getfilesystemencoding()`
* the `ctypes` code above uses `wchar_t`, so `path` is already `str` on Python 3.x and `unicode` on Python 2.x
* on Python 3.x this is a no-op (`hasattr(str(), "decode")` is always `False`)
* on Python 2.x this throws if `path` has "invalid" characters, but by definition it cannot have invalid characters because it has come from the OS. Without changing the codec, "invalid" means "non-ASCII", which is _very_ restrictive

The end result is that if you invoke this code path - for example, by installing Anaconda2 with non-ASCII characters in your username - you will get a `UnicodeEncodeError` while doing an unnecessary decode.

Removing the entire quoted block above is the simplest and most correct fix.

**Comment by nehaljwani** [comment]
I can confirm that this issue exists with the py2 installers. I created a fake user by the name 'AndrésGarcía' and tried installing Miniconda2 to C:\AG and it failed with a traceback:
![screenshot from 2017-12-06 10-53-19](https://user-images.githubusercontent.com/1779189/33646038-ea00a1e6-da73-11e7-8016-83b6674d984a.png)

**Comment by nehaljwani** [comment]
I can confirm that `type(path)` is already `unicode` before hitting this code path in Python2 and `str` in Python3 and the block of code can be removed.

However, even after applying the patch, I got a traceback (not via the installer, but on a local import):
```
(test) C:\Users\AndrésGarcía>python
Python 2.7.14 |Anaconda, Inc.| (default, Nov  8 2017, 13:40:45) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from menuinst.knownfolders import get_folder_path, FOLDERID
<type 'unicode'>
C:\Users\Public\Desktop
<type 'unicode'>
C:\ProgramData\Microsoft\Windows\Start Menu\Programs
<type 'unicode'>
C:\Users\Public\Documents
<type 'unicode'>
C:\Users\AndrésGarcía
<type 'unicode'>
C:\Users\AndrésGarcía\Desktop
<type 'unicode'>
C:\Users\AndrésGarcía\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
<type 'unicode'>
C:\Users\AndrésGarcía\AppData\Roaming\Microsoft\Internet Explorer\Quick Launch
<type 'unicode'>
C:\Users\AndrésGarcía\Documents
<type 'unicode'>
C:\Users\AndrésGarcía
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\AndrésGarcía\Miniconda3\envs\test\lib\site-packages\menuinst\__init__.py", line 23, in <module>
    from .win32 import Menu, ShortCut
  File "C:\Users\AndrésGarcía\Miniconda3\envs\test\lib\site-packages\menuinst\win32.py", line 139, in <module>
    logger.warn('menuinst called from non-root env %s' % (sys.prefix))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 13: ordinal not in range(128)
```

**Comment by nehaljwani** [comment]
Even if we are successful in patching the above, there is one more issue with Conda (Python2) installations. See https://github.com/conda/conda/issues/6401

**Comment by jaimergp** [comment]
This was fixed by https://github.com/conda/menuinst/pull/62
