### ISSUE TITLE
Problem with spaces in paths on windows

### ISSUE THREAD

**Issue by kalefranz** [conda/menuinst#58]
See https://github.com/conda/conda/issues/6704#issuecomment-358450493

**Comment by mbewley** [comment]
This makes the anaconda prompt not work at all (commands "conda" and "anaconda" are not recognised) on windows machines where there are spaces in the installation path (e.g. in the username for a default "single user" install). I think the fix should be just adding some quotes in the right place to the code that produces the shortcuts.

**Comment by huguesv** [comment]
This is a problem for the Anaconda installations we have in Visual Studio 2017. They are installed under `C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64`, etc

and the Anaconda Prompt doesn't work:
```
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\huvalo\Documents>
```

**Comment by msarahan** [comment]
@huguesv, a path nested that deeply is going to cause problems with the path length limit.  Have you not seen these?  I'd be surprised.

I think we have addressed the space issue between recent conda releases and menuinst 1.4.11.  These will be in the looming Anaconda 5.1 installers.  If the VS team would like to test them, please email me - msarahan@anaconda.com

**Comment by zooba** [comment]
@msarahan Thanks, I already have access to those.

I haven't seen path length limit issues, but can't rule them out for sure. That path isn't really much deeper than `C:\Users\my_username_here\AppData\Local\Continuum\anaconda3` (59 vs 66), and usernames certainly vary dramatically in length/spaces/Unicode/etc.

The only other option is a top-level install for all users (`C:\Anaconda3`), which I'm fine with provided the ACLs are correctly set (Administrators have full control, Everyone has read+execute). The inherited ACL when you install in the root directory is that anyone can modify the contents, which is a significant vulnerability and not an appropriate default.

**Comment by huguesv** [comment]
I tested the 5.1 installer and the prompt works after installing into `C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64`

Thanks!
