### ISSUE TITLE
means to disable menu generation for a given instalaltion of conda

### ISSUE THREAD

**Issue by Newtopian** [conda/menuinst#76]
Since menuinst is now a mandatory package when installing conda (at least on windows https://github.com/conda/conda/blob/master/setup.py#L40) once can no longer simply remove menuinst from allowed package as directed here (https://docs.conda.io/projects/conda-build/en/latest/resources/add-win-start-menu-items.html) or by excluding it in the .condarc.  doing so will fail any updates attempted on conda itself (from condarc) or fail installation of conda outright (if done from constructor).
Is there a way one could configure to disable completely start menu creation for a specific conda installation ?

**Comment by sebastianbertoli** [comment]
Would love to know this as well. @Newtopian may I ask if you have figured out a solution for this? Thank you! :)

**Comment by Newtopian** [comment]
Sorry for the late response, just notice this message.
I ended up creating my own installer for Conda through which I was able to get through it.  Don't quite remember the exact details of it. Sadly i've since changed job and I no longer have access to this codebase.  Should I get a flash of memory I'll post it back.  Worked reasonably well considering

**Comment by jaimergp** [comment]
@sebastianbertoli I think `.condarc` [allows](https://github.com/conda/conda/blob/main/conda/base/context.py#L1490-L1495) a `shortcuts: false` option.

**Comment by jaimergp** [comment]
Can also be used per-command with [`--no-shortcuts`](https://github.com/conda/conda/blob/c6ead1bfaf14f6d5274cc05272212b95d55bac27/conda/cli/conda_argparse.py#L1775).

**Comment by sebastianbertoli** [comment]
Thank you!
