### ISSUE TITLE
menuinst called from non-root env

### ISSUE THREAD

**Issue by ReimarBauer** [conda/menuinst#79]
Our windows users recently reported a window popping up, where they need an admin account. 
(https://github.com/Open-MSS/MSS/issues/927)

![install on windows](https://user-images.githubusercontent.com/278728/117567933-ae54cd00-b0be-11eb-9757-c02b4f4fba3e.png)

How can this be handled?

**Comment by sebastianbertoli** [comment]
I have the same problem unfortunately. Any ideas?

**Comment by ReimarBauer** [comment]
In my case, I ignored it, and it seems more like a warning.

**Comment by sebastianbertoli** [comment]
Thanks for the quick reaction @ReimarBauer! I guess that works too. XD If I find another solution, I will let you know. Thanks!
